version: '3.8'

services:
  fastapi:
    build: .
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - studentslessons-db:/app/db
    environment:
      - PYTHONUNBUFFERED=1
      - DB_URL=sqlite:///students_lessons.db
      - ANALYTIC_DB_URL=sqlite+aiosqlite:///./analytics.db
    restart: unless-stopped
    init: true

  bot:
    build: .
    command: python main.py
    environment:
      - PYTHONUNBUFFERED=1
      - DB_URL=sqlite:///students_lessons.db
      - ANALYTIC_DB_URL=sqlite+aiosqlite:///./analytics.db
    volumes:
      - .:/app
      - studentslessons-db:/app/db
    depends_on:
      - fastapi
    restart: unless-stopped
    init: true

volumes:
  studentslessons-db:
